name: oqvt_industrial_entity_management
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  provider: ^6.1.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  syncfusion_flutter_calendar: ^27.1.53

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
